# Generated by Django 6.0.3 on 2026-05-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватарка",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="О себе"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="https://github.com/username",
                        null=True,
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="@username или https://t.me/...",
                        max_length=50,
                        null=True,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
