# Generated by Django 6.0.3 on 2026-05-02 13:23

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("CNY", "Китайский юань"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=120, verbose_name="Slug"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="teams.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория расходов",
                "verbose_name_plural": "Категории расходов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Наименование расхода"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "₽ Российский рубль"),
                            ("USD", "$ Доллар США"),
                            ("EUR", "€ Евро"),
                            ("CNY", "¥ Юань"),
                        ],
                        default="RUB",
                        max_length=3,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Курс на момент создания",
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма в RUB",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата расхода")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="teams.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.expensecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход",
                "verbose_name_plural": "Расходы",
                "ordering": ["-date", "-amount"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "slug"),
                name="unique_expense_slug_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("team", "slug"),
                name="unique_expense_slug_per_team",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "date"], name="expenses_ex_user_id_713a9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="expenses_ex_categor_20264a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date"], name="expenses_ex_date_17a2b2_idx"),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("team__isnull", True), ("user__isnull", False)),
                    models.Q(("team__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="expense_belongs_to_either_user_or_team",
            ),
        ),
    ]
