# Generated by Django 6.0.3 on 2026-05-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=120, verbose_name="Slug"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_categories",
                        to="teams.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория задач",
                "verbose_name_plural": "Категории задач",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название задачи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (100, "К выполнению"),
                            (75, "В работе"),
                            (50, "Выполнено"),
                            (25, "В архиве"),
                        ],
                        default=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (25, "Низкий"),
                            (50, "Средний"),
                            (75, "Высокий"),
                            (100, "Срочный"),
                        ],
                        default=50,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="teams.team",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.taskcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="taskcategory",
            index=models.Index(fields=["user"], name="tasks_taskc_user_id_f1a3a4_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcategory",
            index=models.Index(fields=["team"], name="tasks_taskc_team_id_2dc712_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "slug"),
                name="unique_task_slug_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("team", "slug"),
                name="unique_task_slug_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("team__isnull", True), ("user__isnull", False)),
                    models.Q(("team__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="task_category_belongs_to_either_user_or_team",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "priority"], name="tasks_task_status_01b536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["team", "status"], name="tasks_task_team_id_e2b702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status"], name="tasks_task_user_id_c0fce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["deadline"], name="tasks_task_deadlin_736196_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("team__isnull", True), ("user__isnull", False)),
                    models.Q(("team__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="task_belongs_to_either_user_or_team",
            ),
        ),
    ]
